//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailHoursMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RetailWebEntities : DbContext
    {
        public RetailWebEntities()
            : base("name=RetailWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblRtlHour> tblRtlHours { get; set; }
    
        public virtual ObjectResult<spRtlHours_GetHours_Result> spRtlHours_GetHours()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRtlHours_GetHours_Result>("spRtlHours_GetHours");
        }
    
        public virtual int spRtlHours_InsertHours(string weekdayHours, string weekendHours, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, ObjectParameter strReturn_Text)
        {
            var weekdayHoursParameter = weekdayHours != null ?
                new ObjectParameter("WeekdayHours", weekdayHours) :
                new ObjectParameter("WeekdayHours", typeof(string));
    
            var weekendHoursParameter = weekendHours != null ?
                new ObjectParameter("WeekendHours", weekendHours) :
                new ObjectParameter("WeekendHours", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRtlHours_InsertHours", weekdayHoursParameter, weekendHoursParameter, fromDateParameter, toDateParameter, strReturn_Text);
        }
    }
}
